### ISSUE TITLE
Volume control should take "+" and "-" as arguments

### ISSUE THREAD

**Issue by sudeepsidhu** [talecK/TCMusicBot#16]
Should be very easy to achieve with regexes. The current volume controls are really tedious to use. Give each sign a value of 4 (or something that creates a perceptible difference), type determines the sign. 

So:
vol++ will increase by 8
vol- will decrease by 4

We can still have an argument less volume command return the current volume.

I've wanted to do this for a while now. But never go around to it.

B-Eazy, you're my only hope.

**Comment by rickywiens** [comment]
done
